// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_over_9000 = "CgkIloSc-_gREAIQDA"; // <GPGSID>
        public const string achievement_50_zombies_slain = "CgkIloSc-_gREAIQBA"; // <GPGSID>
        public const string achievement_100_zombies_slain = "CgkIloSc-_gREAIQBg"; // <GPGSID>
        public const string achievement_world_thanks_for_the_new_nuke = "CgkIloSc-_gREAIQBw"; // <GPGSID>
        public const string achievement_200_zombies_slain = "CgkIloSc-_gREAIQDQ"; // <GPGSID>
        public const string achievement_500_zombies_slain = "CgkIloSc-_gREAIQDw"; // <GPGSID>
        public const string achievement_zombies_slain = "CgkIloSc-_gREAIQAQ"; // <GPGSID>
        public const string achievement_new_mr_drumb = "CgkIloSc-_gREAIQBQ"; // <GPGSID>
        public const string achievement_tower_upgrade = "CgkIloSc-_gREAIQEA"; // <GPGSID>
        public const string achievement_not_so_fast_anymore = "CgkIloSc-_gREAIQCw"; // <GPGSID>
        public const string achievement_new_game = "CgkIloSc-_gREAIQAA"; // <GPGSID>
        public const string achievement_gunner = "CgkIloSc-_gREAIQCQ"; // <GPGSID>
        public const string achievement_oh_theres_tactics_in_this_game = "CgkIloSc-_gREAIQDg"; // <GPGSID>
        public const string leaderboard_artdleaderboard = "CgkIloSc-_gREAIQAg"; // <GPGSID>
        public const string achievement_missiles_op = "CgkIloSc-_gREAIQCg"; // <GPGSID>
        public const string achievement_zombie_epidemic_always_wins = "CgkIloSc-_gREAIQCA"; // <GPGSID>

}

